### ISSUE TITLE
### Get all Spots

### ISSUE THREAD

**Issue by JohnW44** [traviswood1/API-project#7]
Returns all the spots.

- [x] Seed data exists in the database for spots to be returned.
- [x] Successful response includes each spot in the database.
- [x] Spot data returned includes the `id`, `ownerId`, `address`, `city`,
  `state`, `country`, `lat`, `lng`, `name`, `description`, `price`, `createdAt`,
  `updatedAt`, `previewImage`, and `avgRating`

**Comment by traviswood1** [comment]
need to add previewImage and avgRating to Spot data
